from .document import Document as Document
from .genre import Genre as Genre
from .language import Language as Language
from .part import Part as Part
from .place import Place as Place
from .repository import Repository as Repository
from .scripta import Scripta as Scripta
from .story import Story as Story
from .storyverse import Storyverse as Storyverse
from .text import Text as Text
from .witness import Witness as Witness
