from .has_genre import HasGenre
from .has_language import HasLanguage
from .has_writing_style import HasWritingStyle
from .is_derived_from import IsDerivedFrom
from .is_embodied_in import IsEmbodiedIn
from .is_located import IsLocated
from .is_materialized_on import IsMaterializedOn
from .is_part_of import IsPartOf
from .is_realized_in import IsRealizedIn
